//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP05Gapeev.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int IdOperations { get; set; }
        public int IdFirmOperations { get; set; }
        public int IdMonthOperations { get; set; }
        public decimal BuyOperations { get; set; }
        public decimal SaleOperations { get; set; }
        public int PurchasedOperations { get; set; }
        public int SalesOperations { get; set; }
        public Nullable<decimal> IncomeOperations { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Month Month { get; set; }
    }
}
